dist: xenial

services:
        - docker

script:
        - docker build -t zabbix-server .

deploy:
        provider: script
        script: bash deploy_dockerhub.sh
        on:
                branch: master
