env:
  - DOCKER_NAME_IMAGE=zabser-t1

sudo: required

services:
  - docker

script:
  - docker build -t $DOCKER_NAME_IMAGE .
  - docker run -d -p 127.0.0.1:7777:80 $DOCKER_NAME_IMAGE
  - sleep 10
  - docker ps
  - curl -Is 127.0.0.1:7777

    #after_success:
    #  - test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_dockerhub.sh

